events {}

http {
    limit_req_zone $binary_remote_addr zone=main_limit:10m rate=15r/s;
    limit_req_status 429;

    server {
        listen 80;
        # ==========================================
        # 1. Aplikasi Testing (User) - Dilindungi Auth
        # ==========================================
        location / {
            limit_req zone=main_limit burst=20 nodelay;

            auth_request /internal_ip_check;

            proxy_pass http://user_app:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /internal_ip_check {
            internal;
            
            # GANTI $remote_addr dengan $http_x_forwarded_for
            proxy_pass http://ml_engine:5000/api/blacklist/check?ip=$http_x_forwarded_for;
            
            proxy_pass_request_body off; 
            proxy_set_header Content-Length "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. Endpoint API (Abaikan atau tetap pasang sesuai kebutuhan)
        location /api {
            proxy_pass http://ml_engine:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}