events {}

http {
    server {
        listen 80;

        # 1. Aplikasi Testing (User)
        location / {
            proxy_pass http://user_app:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # TAMBAHKAN BARIS INI:
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Endpoint khusus untuk dashboard/monitoring
        location /dashboard {
            # UBAH PORT DARI 3000 KE 5000:
            proxy_pass http://ml_engine:5000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. Tambahkan juga untuk API log (agar komunikasi lancar)
        location /api {
            proxy_pass http://ml_engine:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
